[build]
# idea/wish: to get reproducable blobs
filehash = false
offline = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i input.css -o style/output.css"]
